---
- name: check out git repository
  become: true
  become_user: "{{ taiga_user }}"
  git:
    repo: "{{ taiga_git_mirror }}/{{ taiga_events_repo }}"
    dest: "{{ taiga_user_home }}/{{ taiga_events_checkout_dir }}"
    version: "{{ taiga_events_version }}"
  notify:
    - "restart taiga-events (via {{ taiga_service_manager }})"
  tags:
    - install
    - events-install

- name: deploy configuration file
  become: true
  become_user: "{{ taiga_user }}"
  template:
    mode: '0644'
    src: config.json.j2
    dest: "{{ taiga_user_home }}/{{ taiga_events_checkout_dir }}/config.json"
  notify:
    - "restart taiga-events (via {{ taiga_service_manager }})"
  tags:
    - config
    - events-config
    - offline

- name: install global NPM modules
  become: true
  become_user: root
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - coffee-script
  tags:
    - install
    - events-install

- name: install local NPM modules
  become: true
  become_user: "{{ taiga_user }}"
  npm:
    path: "{{ taiga_user_home }}/{{ taiga_events_checkout_dir }}"
  tags:
    - install
    - events-install

- include: "{{ taiga_service_manager }}.yml"
